### ISSUE TITLE
Update the approveOamRequest Service for the file does not exit and ALL method 

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/AdministratorAdministration#173]
Allow the method type is equal to ALL
 If the File does not exit respose should be a UNKOWN
As of know if file does not exit it is giving AUTHORIZATION_CODE_UNKNOWN but it should Change to UNKOWN

**Comment by ManasaBM1** [comment]
Enhancement of code

**Comment by PrathibaJee** [comment]
If the application data file itself is not available , then this problem is related to server side. This will make AA to not behave as expected for all the connected clients.
In this case , the server should fail to process the request and should give an internal server error 500.
This transparency will also help us to identify the underlying problem.
