### ISSUE TITLE
OAS : callback uri definition : /v1/inquire-oam-request-approvals

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AdministratorAdministration#33]
Problem:

Operation-name is statically defined in callback request "NewApplicationCausesRequestForInquiringOamRequestApprovals"

Proposal:

Line 985 to be changed from "https://{$request.body#application-address}:{$request.body#application-port}/v1/inquire-oam-request-approvals" to "https://{$request.body#application-address}:{$request.body#application-port}[/core-model-1-4:control-construct/logical-termination-point=aa-0-0-1-op-s-0005/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]"

Related issue : https://github.com/openBackhaul/OamLog/issues/6

**Comment by openBackhaul** [comment]
There is a couple of aspects to be clarified:
- All URIs containing references into the RequestBody (e.g. _{$request.body#application-port}_) have been corrected in such a way that references are pointing into the internal data structure instead. Reason: Data sent in the RequestBody has to update the internal data structure first and the consequent requests (callbacks) have to be sent afterwards. The updated URI can be found in line 898 of the AA OAS.
- The proposed solution is using an OperationServer uuid in a path, which is ending at an OperationClient attribute. This is definitively incorrect.
- The _/v1/inquire-oam-request-approvals_ OperationClient has 8 occurrences (e.g. _aa-2-0-0-op-c-im-ro-2-0-0-004_ or _aa-2-0-0-op-c-im-tar-1-0-0-000_) in the CONFIGfile.
- A generic representation of the UUID would look like _aa-2-0-0-op-c-im-\*-\*-\*-\*-\*_, which I found not very meaningful. This is why I decided to put the concrete operation name, which will potentially outdate.

@IswaryaaS : If you would agree, please close the issue. 
Otherwise, please guide the discussion by additional reason, question or doubt and assign the issue back to openBackhaul.

**Comment by IswaryaaS** [comment]
Similar to [EATL_pull#111](https://github.com/openBackhaul/ExecutionAndTraceLog/pull/111), can we also update the sequence number for /v1/inquire-oam-request-approvals operation-clients of all applications to 004 (similar to RO)

Then, the uuid(s) of operation-client//v1/inquire-oam-request-approvals of TAR, EATL and other applications will become aa-2-0-0-op-c-im-tar-1-0-0-004, aa-2-0-0-op-c-im-eatl-2-0-0-004 etc.., with common sequence number 004. so that we can define a pattern like aa-2-0-0-op-c-im-\*-\*-\*-\*-004. Please let me know your thoughts.
