### ISSUE TITLE
OAS : /v1/bequeath-your-data-and-die : callback : reference path needs update

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/AdministratorAdministration#37]
Error description:
In callback "_PromptForBequeathingDataCausesRObeingRequestedToNotifyApprovalsOfNewApplicationsToNewRelease_" and "_PromptForBequeathingDataCausesRObeingRequestedToNotifyWithdrawnApprovalsToNewRelease_", we have request-body attribute "_subscriber-operation_", the reference path under description of the attribute needs an update. The path is intended to refer an operation-server ltp (aa-0-0-1-op-s-3001 and aa-0-0-1-op-s-3002), but the proceeding path points to operation-client.

Possible solution:
In the description, path needs an update to point to operation-server-interface-capability/operation-name as below.

For PromptForBequeathingDataCausesRObeingRequestedToNotifyApprovalsOfNewApplicationsToNewRelease, the current description contains /core-model-1-4:control-construct/logical-termination-point=aa-0-0-1-op-s-3001/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name, which actually would be
_/core-model-1-4:control-construct/logical-termination-point=aa-0-0-1-op-s-3001/layer-protocol=0/operation-server-interface-1-0:operation-server-interface-pac/operation-server-interface-capability/operation-name_

For PromptForBequeathingDataCausesRObeingRequestedToNotifyWithdrawnApprovalsToNewRelease, the description would be updated as
_/core-model-1-4:control-construct/logical-termination-point=aa-0-0-1-op-s-3002/layer-protocol=0/operation-server-interface-1-0:operation-server-interface-pac/operation-server-interface-capability/operation-name_

Note: aa-0-0-1-op-s-3001 refers to /v1/regard-application and aa-0-0-1-op-s-3002 refers to /v1/disregard-application

Related issues:
https://github.com/openBackhaul/RegistryOffice/issues/91
https://github.com/openBackhaul/TypeApprovalRegister/issues/40
https://github.com/openBackhaul/ExecutionAndTraceLog/issues/41
https://github.com/openBackhaul/OamLog/issues/38
https://github.com/openBackhaul/ApplicationLayerTopology/issues/60
https://github.com/openBackhaul/OperationKeyManagement/issues/28

**Comment by openBackhaul** [comment]
In general:
Some callback is describing a request, which is sent by the application.
This cannot be described by an own OperationServer, but must be an OperationClient.

In regards with PromptForBequeathingDataCausesRObeingRequestedToNotifyApprovalsOfNewApplicationsToNewRelease:
Reference of operation-name has been changed towards: _/core-model-1-4:control-construct/logical-termination-point=**aa-2-0-0-op-c-im-ro-2-0-0-000**/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name_

In regards with PromptForBequeathingDataCausesRObeingRequestedToNotifyWithdrawnApprovalsToNewRelease:
Reference of operation-name has been changed towards: _/core-model-1-4:control-construct/logical-termination-point=**aa-2-0-0-op-c-im-ro-2-0-0-001**/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name_

@IswaryaaS: If you would agree, please close this issue.
Otherwise, please guide the discussion by additional reason, question or doubt and assign the issue back to openBackhaul.

**Comment by IswaryaaS** [comment]
Sorry for the confusion. The description in issue might not be clear.
In PromptForBequeathingDataCausesRObeingRequestedToNotifyApprovalsOfNewApplicationsToNewRelease and PromptForBequeathingDataCausesRObeingRequestedToNotifyWithdrawnApprovalsToNewRelease, we have attributes in request body called "subscriber-operation". In the description of this attribute "subscriber-operation", the uuid is pointing to "aa-2-0-0-op-s-is-001" and "aa-2-0-0-op-s-is-002", but the path reference is pointing to operation-client.
This needs to be updated to operation-server/operation-name (line 265 and 361)

**Comment by openBackhaul** [comment]
Yes, agree to your proposal.
Changed as proposed.
Many thanks for indicating.
